name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: click on me to view progress
    runs-on: windows-2025
    
    steps:
      - name: Download
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/candycane2/lite_manager_win/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: con
        run: cmd /c show.bat

      - name: meow

        run: cmd /c loop.bat
